apiVersion: v1
kind: Service
metadata:
  name: svc-my-maven-app-dev  # Change this for staging/prod
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: my-maven-app
